<!--
	ðŸ‘‹ðŸ½ Hey there,
	Thank you for contributing to a Foretag project; before you proceed, here are a few notes:

	- You agree to our code of conduct
	- You understand and agree to the LICENSE of this project

	We appreciate your contribution to helping us in our mission to accelerate human progress.
-->

<!-- Please provide a summary of your changes for the title -->
<!-- NOTE: please do not leave any section empty, instead write N/A and if possible, why its not applicable -->

### Description

<!-- Add a detailed description of how your changes affect the user and provide additional context where necessary -->

### Components

<!-- 
For example, if your PR is related to the `CLI` and `Server`, please add:

- Server
- CLI
 -->

### Related issues

<!-- Please link to any issues related to this PR by adding the issue number i.e. #1234 -->

### Implementation

<!-- Add as much detail as possible on how this PR solves or fixes the issues, the design, approach and any relevant resources -->

### Testing

<!-- If this PR is related to a feature request, add any steps to test the feature successfully -->
<!-- If this PR is a bug fix, add any steps to verify the fix -->

<!-- 1. Step 1 -->
<!-- 2. Step 2 -->
<!-- 3. Step 3 -->

### Limitations, bugs & workarounds

<!-- If irrelevant, please delete this section -->
<!-- else, please add any known bugs, limitations and workarounds relating to this PR -->

### Breaking changes

<!-- **Breaking Changes**  -->
<!-- No Breaking Changes  -->

<!-- If your breaking changes are not listed then please add some context on what exactly is being changed and how it impacts users -->