name: 🚀 Feature request
description: Suggest an idea, feature or integration
title: "Feature Request: "
labels:
    - "kind/enhancement"
    - "support/needs-triage"

body:
    - type: markdown
      attributes:
          value: |
              👋🏽 Thanks for filing this feature request, here is a preliminary checklist

    - type: checkboxes
      id: preliminary-checklist
      attributes:
          label: Preliminary checklist
          options:
              - label: I understand that all communication must be in English
                required: true
              - label: I read the [Documentation](https://engineering.foret.ag)
                required: true
              - label: I read the [Contributing guide](https://github.com/ForetagInc/.github/blob/master/CONTRIBUTING.md)
                required: true
              - label: I agree to follow the [Code of Conduct](https://github.com/ForetagInc/.github/blob/master/CODE_OF_CONDUCT.md)
                required: true
              - label: I searched the issues and discussions but couldn't find anything (or linked relevant results below)
                required: true

    - type: textarea
      id: problem
      attributes:
          label: Problem
          description: Please describe the problem you are trying to solve here.
          placeholder: I'm always frustrated when...
      validations:
          required: true

    - type: textarea
      id: solution
      attributes:
          label: Solution
          description: What should happen? Please describe the desired behavior.
          placeholder: When I click the sync button the data should sync
      validations:
          required: true

    - type: textarea
      id: alternatives
      attributes:
          label: Alternatives
          description: What are the alternative solutions? Can this be solved in a different way?
          placeholder: |
              The problem could be solved body:
              - Creating an external plugin
              - Integrating the feature directly into the codebase

              Some tips:
              - Include as much detail about the implementation and pros and cons of each approach
              - Timebox if possible
              - Where possible, add sample pseudo code
      validations:
          required: false

    - type: dropdown
      id: contribution
      attributes:
          label: Contribution
          description: If the feature is approved, would you be willing to submit a PR?
          multiple: false
          options:
              - "Yes, I will work on a PR"
              - "No, I cannot contribute further"
      validations:
          required: true

    - type: input
      id: keywords
      attributes:
          label: Keywords
          description:
              What keywords did you use when trying to find this feature?
              List them here so people in the future can find this one more easily.
          placeholder: i.e. integration, graphql, grpc
      validations:
          required: false
