name: "Pipeline"
on:
    release:
        types: [published]

jobs:
    ci:
        name: "CI"
        runs-on: "ubuntu-latest"
        steps:
            - uses: "actions/checkout@v3"
              with:
                  fetch-depth: 0
            - uses: "actions/setup-node@v3"
            - run: "npm install --immutable"
            - run: "npx --yes @moonrepo/cli@latest ci"
            - uses: "moonrepo/run-report-action@v1"
              if: success() || failure()
              with:
                  access-token: ${{ secrets.GITHUB_TOKEN }}
